### PR TITLE
Add ugly bulk indexing

### PR DESCRIPTION
**Pull request by mwotton**
I've added a few utility functions (create/delete index), a bulk indexing function, and tests to cover them.
This is intended as a starting point for discussion - parts are clumsy at best. It does appear to do more or less the right thing though, even if it's not using anything clever like pipes or conduits.

### CODE REVIEW

**Comment by ocharles** [comment]
Could you rebase all of this into a single commit?

**Comment by ocharles** [comment]
Otherwise looks good and I'd love to merge this! Thanks :)

**Comment by mwotton** [comment]
yep, no probs

**Comment by ocharles** [comment]
Perfect, thanks!

**Pull request merged**
